//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ternium.Sio_Server.Language {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ternium.Sio_Server.Language.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alambrón.
        /// </summary>
        public static string Alambrón {
            get {
                return ResourceManager.GetString("Alambrón", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alambrón.
        /// </summary>
        public static string Alambrón1 {
            get {
                return ResourceManager.GetString("Alambrón1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Todos.
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aprobado.
        /// </summary>
        public static string Approved {
            get {
                return ResourceManager.GetString("Approved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Productividad Disponible.
        /// </summary>
        public static string AvailableProductivity {
            get {
                return ResourceManager.GetString("AvailableProductivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiempo Disponible.
        /// </summary>
        public static string AvailableTime {
            get {
                return ResourceManager.GetString("AvailableTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T. Disp..
        /// </summary>
        public static string AvailableTimeAbbr {
            get {
                return ResourceManager.GetString("AvailableTimeAbbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bienvenidos.
        /// </summary>
        public static string Bienvenidos {
            get {
                return ResourceManager.GetString("Bienvenidos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bienvenidos.
        /// </summary>
        public static string Bienvenidos1 {
            get {
                return ResourceManager.GetString("Bienvenidos1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contraer/Expandir.
        /// </summary>
        public static string CollapseExpand {
            get {
                return ResourceManager.GetString("CollapseExpand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comentarios.
        /// </summary>
        public static string Comments {
            get {
                return ResourceManager.GetString("Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Concepto.
        /// </summary>
        public static string Concept {
            get {
                return ResourceManager.GetString("Concept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cortina.
        /// </summary>
        public static string Cortina {
            get {
                return ResourceManager.GetString("Cortina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cortina.
        /// </summary>
        public static string Cortina1 {
            get {
                return ResourceManager.GetString("Cortina1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cuadrado.
        /// </summary>
        public static string Cuadrado {
            get {
                return ResourceManager.GetString("Cuadrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cuadrado.
        /// </summary>
        public static string Cuadrado1 {
            get {
                return ResourceManager.GetString("Cuadrado1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado Actual.
        /// </summary>
        public static string CurrentStatus {
            get {
                return ResourceManager.GetString("CurrentStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defecto.
        /// </summary>
        public static string Defect {
            get {
                return ResourceManager.GetString("Defect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defectos.
        /// </summary>
        public static string Defects {
            get {
                return ResourceManager.GetString("Defects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Degradado.
        /// </summary>
        public static string Degraded {
            get {
                return ResourceManager.GetString("Degraded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duela.
        /// </summary>
        public static string Duela {
            get {
                return ResourceManager.GetString("Duela", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duela.
        /// </summary>
        public static string Duela1 {
            get {
                return ResourceManager.GetString("Duela1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duración.
        /// </summary>
        public static string Duration {
            get {
                return ResourceManager.GetString("Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acero laminado en caliente.
        /// </summary>
        public static string Ejem_Prod1 {
            get {
                return ResourceManager.GetString("Ejem_Prod1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acero laminado en caliente.
        /// </summary>
        public static string Ejem_Prod11 {
            get {
                return ResourceManager.GetString("Ejem_Prod11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variedad de diámetros.
        /// </summary>
        public static string Ejem_Prod2 {
            get {
                return ResourceManager.GetString("Ejem_Prod2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variedad de diámetros.
        /// </summary>
        public static string Ejem_Prod21 {
            get {
                return ResourceManager.GetString("Ejem_Prod21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resistente.
        /// </summary>
        public static string Ejem_Prod3 {
            get {
                return ResourceManager.GetString("Ejem_Prod3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resistente.
        /// </summary>
        public static string Ejem_Prod31 {
            get {
                return ResourceManager.GetString("Ejem_Prod31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corrugado especial.
        /// </summary>
        public static string Ejem_Prod4 {
            get {
                return ResourceManager.GetString("Ejem_Prod4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corrugado especial.
        /// </summary>
        public static string Ejem_Prod41 {
            get {
                return ResourceManager.GetString("Ejem_Prod41", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resistencia estructural.
        /// </summary>
        public static string Ejem_Prod5 {
            get {
                return ResourceManager.GetString("Ejem_Prod5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resistencia estructural.
        /// </summary>
        public static string Ejem_Prod51 {
            get {
                return ResourceManager.GetString("Ejem_Prod51", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variedad de Calibres.
        /// </summary>
        public static string Ejem_Prod6 {
            get {
                return ResourceManager.GetString("Ejem_Prod6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variedad de Calibres.
        /// </summary>
        public static string Ejem_Prod61 {
            get {
                return ResourceManager.GetString("Ejem_Prod61", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Durabilidad y resistencia estructural.
        /// </summary>
        public static string Ejem_Text1 {
            get {
                return ResourceManager.GetString("Ejem_Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Durabilidad y resistencia estructural.
        /// </summary>
        public static string Ejem_Text11 {
            get {
                return ResourceManager.GetString("Ejem_Text11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Productos derivados de laminación en caliente de palanquillas. Su sección es circular y la superficie lisa o corrugada..
        /// </summary>
        public static string Ejem_Text2 {
            get {
                return ResourceManager.GetString("Ejem_Text2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Productos derivados de laminación en caliente de palanquillas. Su sección es circular y la superficie lisa o corrugada..
        /// </summary>
        public static string Ejem_Text21 {
            get {
                return ResourceManager.GetString("Ejem_Text21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Productos y Servicios.
        /// </summary>
        public static string Ejem_Tit1 {
            get {
                return ResourceManager.GetString("Ejem_Tit1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Productos y Servicios.
        /// </summary>
        public static string Ejem_Tit11 {
            get {
                return ResourceManager.GetString("Ejem_Tit11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aceros Largos.
        /// </summary>
        public static string Ejem_Tit2 {
            get {
                return ResourceManager.GetString("Ejem_Tit2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aceros Largos.
        /// </summary>
        public static string Ejem_Tit21 {
            get {
                return ResourceManager.GetString("Ejem_Tit21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resistencia y variedad de formas.
        /// </summary>
        public static string Ejem2_Text1 {
            get {
                return ResourceManager.GetString("Ejem2_Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resistencia y variedad de formas.
        /// </summary>
        public static string Ejem2_Text11 {
            get {
                return ResourceManager.GetString("Ejem2_Text11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Los perfiles Ternium son fabricados con acero procesado en roladoras y molinos, con acabado negro, galvanizado y pintado. Disponibles en una amplia variedad de diseños para usos específicos, que van desde la periferia para ventanas, marcos y puertas, hasta polines y perfiles estructurales..
        /// </summary>
        public static string Ejem2_Text2 {
            get {
                return ResourceManager.GetString("Ejem2_Text2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Los perfiles Ternium son fabricados con acero procesado en roladoras y molinos, con acabado negro, galvanizado y pintado. Disponibles en una amplia variedad de diseños para usos específicos, que van desde la periferia para ventanas, marcos y puertas, hasta polines y perfiles estructurales..
        /// </summary>
        public static string Ejem2_Text21 {
            get {
                return ResourceManager.GetString("Ejem2_Text21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Productos.
        /// </summary>
        public static string Ejem2_Tit1 {
            get {
                return ResourceManager.GetString("Ejem2_Tit1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Productos.
        /// </summary>
        public static string Ejem2_Tit11 {
            get {
                return ResourceManager.GetString("Ejem2_Tit11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perfiles.
        /// </summary>
        public static string Ejem2_Tit2 {
            get {
                return ResourceManager.GetString("Ejem2_Tit2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perfiles.
        /// </summary>
        public static string Ejem2_Tit21 {
            get {
                return ResourceManager.GetString("Ejem2_Tit21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fin.
        /// </summary>
        public static string End {
            get {
                return ResourceManager.GetString("End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Si el error persiste, contacte a la Mesa de Ayuda..
        /// </summary>
        public static string ErrorContactHelpDesk {
            get {
                return ResourceManager.GetString("ErrorContactHelpDesk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ha ocurrido un error interno en el servidor..
        /// </summary>
        public static string ErrorInternalServer {
            get {
                return ResourceManager.GetString("ErrorInternalServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor, intente realizar la operación más tarde..
        /// </summary>
        public static string ErrorTryLater {
            get {
                return ResourceManager.GetString("ErrorTryLater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtro.
        /// </summary>
        public static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genuina.
        /// </summary>
        public static string Genuine {
            get {
                return ResourceManager.GetString("Genuine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Producción Genuina.
        /// </summary>
        public static string GenuineProduction {
            get {
                return ResourceManager.GetString("GenuineProduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hr.
        /// </summary>
        public static string HourAbbr {
            get {
                return ResourceManager.GetString("HourAbbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inicio.
        /// </summary>
        public static string Inicio {
            get {
                return ResourceManager.GetString("Inicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inicio.
        /// </summary>
        public static string Inicio1 {
            get {
                return ResourceManager.GetString("Inicio1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Español.
        /// </summary>
        public static string L_Español {
            get {
                return ResourceManager.GetString("L_Español", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Español.
        /// </summary>
        public static string L_Español1 {
            get {
                return ResourceManager.GetString("L_Español1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingles.
        /// </summary>
        public static string L_Ingles {
            get {
                return ResourceManager.GetString("L_Ingles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingles.
        /// </summary>
        public static string L_Ingles1 {
            get {
                return ResourceManager.GetString("L_Ingles1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Japones.
        /// </summary>
        public static string L_Japones {
            get {
                return ResourceManager.GetString("L_Japones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Japones.
        /// </summary>
        public static string L_Japones1 {
            get {
                return ResourceManager.GetString("L_Japones1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lineas.
        /// </summary>
        public static string L_LineasTooltip {
            get {
                return ResourceManager.GetString("L_LineasTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lineas.
        /// </summary>
        public static string L_LineasTooltip1 {
            get {
                return ResourceManager.GetString("L_LineasTooltip1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&lt;br/&gt;I&lt;br/&gt;N&lt;br/&gt;E&lt;br/&gt;A&lt;br/&gt;S.
        /// </summary>
        public static string L_LineasVertical {
            get {
                return ResourceManager.GetString("L_LineasVertical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&lt;br/&gt;I&lt;br/&gt;N&lt;br/&gt;E&lt;br/&gt;A&lt;br/&gt;S.
        /// </summary>
        public static string L_LineasVertical1 {
            get {
                return ResourceManager.GetString("L_LineasVertical1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logo Casa.
        /// </summary>
        public static string L_LogoCasa {
            get {
                return ResourceManager.GetString("L_LogoCasa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logo Casa.
        /// </summary>
        public static string L_LogoCasa1 {
            get {
                return ResourceManager.GetString("L_LogoCasa1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disculpe las molestias, esta pagina esta en construcción..
        /// </summary>
        public static string L_MsgEnConstruccion {
            get {
                return ResourceManager.GetString("L_MsgEnConstruccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disculpe las molestias, esta pagina esta en construcción..
        /// </summary>
        public static string L_MsgEnConstruccion1 {
            get {
                return ResourceManager.GetString("L_MsgEnConstruccion1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es posible que haya ocurrido un error inesperado..
        /// </summary>
        public static string L_MsgErrorApp1 {
            get {
                return ResourceManager.GetString("L_MsgErrorApp1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es posible que haya ocurrido un error inesperado..
        /// </summary>
        public static string L_MsgErrorApp11 {
            get {
                return ResourceManager.GetString("L_MsgErrorApp11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Los administradores del sistema han sido notificados de este evento..
        /// </summary>
        public static string L_MsgErrorApp2 {
            get {
                return ResourceManager.GetString("L_MsgErrorApp2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Los administradores del sistema han sido notificados de este evento..
        /// </summary>
        public static string L_MsgErrorApp21 {
            get {
                return ResourceManager.GetString("L_MsgErrorApp21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lamentamos los inconvenientes ocasionados..
        /// </summary>
        public static string L_MsgErrorApp3 {
            get {
                return ResourceManager.GetString("L_MsgErrorApp3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lamentamos los inconvenientes ocasionados..
        /// </summary>
        public static string L_MsgErrorApp31 {
            get {
                return ResourceManager.GetString("L_MsgErrorApp31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disculpa, ocurrió un error al procesar su solicitud..
        /// </summary>
        public static string L_MsgErrorGral {
            get {
                return ResourceManager.GetString("L_MsgErrorGral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disculpa, ocurrió un error al procesar su solicitud..
        /// </summary>
        public static string L_MsgErrorGral1 {
            get {
                return ResourceManager.GetString("L_MsgErrorGral1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lo sentimos, usted no tiene accesso a esta caracteristica del sistema o no ingresó su usuario/clave..
        /// </summary>
        public static string L_MsgSinAcceso {
            get {
                return ResourceManager.GetString("L_MsgSinAcceso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lo sentimos, usted no tiene accesso a esta caracteristica del sistema o no ingresó su usuario/clave..
        /// </summary>
        public static string L_MsgSinAcceso1 {
            get {
                return ResourceManager.GetString("L_MsgSinAcceso1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Piso de Planta.
        /// </summary>
        public static string L_PisodePlanta {
            get {
                return ResourceManager.GetString("L_PisodePlanta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Piso de Planta.
        /// </summary>
        public static string L_PisodePlanta1 {
            get {
                return ResourceManager.GetString("L_PisodePlanta1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portugues.
        /// </summary>
        public static string L_Portugues {
            get {
                return ResourceManager.GetString("L_Portugues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portugues.
        /// </summary>
        public static string L_Portugues1 {
            get {
                return ResourceManager.GetString("L_Portugues1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abrir.
        /// </summary>
        public static string L_SliderAbrir {
            get {
                return ResourceManager.GetString("L_SliderAbrir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abrir.
        /// </summary>
        public static string L_SliderAbrir1 {
            get {
                return ResourceManager.GetString("L_SliderAbrir1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cerrar.
        /// </summary>
        public static string L_SliderCerrar {
            get {
                return ResourceManager.GetString("L_SliderCerrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cerrar.
        /// </summary>
        public static string L_SliderCerrar1 {
            get {
                return ResourceManager.GetString("L_SliderCerrar1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nivel 1.
        /// </summary>
        public static string Level1 {
            get {
                return ResourceManager.GetString("Level1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nivel 2.
        /// </summary>
        public static string Level2 {
            get {
                return ResourceManager.GetString("Level2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nivel 3.
        /// </summary>
        public static string Level3 {
            get {
                return ResourceManager.GetString("Level3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marco.
        /// </summary>
        public static string Marco {
            get {
                return ResourceManager.GetString("Marco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marco.
        /// </summary>
        public static string Marco1 {
            get {
                return ResourceManager.GetString("Marco1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material.
        /// </summary>
        public static string Material {
            get {
                return ResourceManager.GetString("Material", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microdemora por hora.
        /// </summary>
        public static string MicrodelayPerHour {
            get {
                return ResourceManager.GetString("MicrodelayPerHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiempo Neto.
        /// </summary>
        public static string NetTime {
            get {
                return ResourceManager.GetString("NetTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T. Neto.
        /// </summary>
        public static string NetTimeAbbr {
            get {
                return ResourceManager.GetString("NetTimeAbbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utilización Neta.
        /// </summary>
        public static string NetUtilization {
            get {
                return ResourceManager.GetString("NetUtilization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Util. Neta.
        /// </summary>
        public static string NetUtilizationAbbr {
            get {
                return ResourceManager.GetString("NetUtilizationAbbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número.
        /// </summary>
        public static string Number {
            get {
                return ResourceManager.GetString("Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Observaciones.
        /// </summary>
        public static string Observations {
            get {
                return ResourceManager.GetString("Observations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paquete.
        /// </summary>
        public static string Package {
            get {
                return ResourceManager.GetString("Package", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Página {0} de {1}.
        /// </summary>
        public static string PageOfX {
            get {
                return ResourceManager.GetString("PageOfX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pasamanos.
        /// </summary>
        public static string Pasamanos {
            get {
                return ResourceManager.GetString("Pasamanos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pasamanos.
        /// </summary>
        public static string Pasamanos1 {
            get {
                return ResourceManager.GetString("Pasamanos1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Porcentaje.
        /// </summary>
        public static string Percentage {
            get {
                return ResourceManager.GetString("Percentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Producción.
        /// </summary>
        public static string Producción {
            get {
                return ResourceManager.GetString("Producción", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Producción.
        /// </summary>
        public static string Producción1 {
            get {
                return ResourceManager.GetString("Producción1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Producidos en Turno Seleccionado.
        /// </summary>
        public static string ProducedInSelectedShift {
            get {
                return ResourceManager.GetString("ProducedInSelectedShift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cantidad Bobinas Fix Producidas.
        /// </summary>
        public static string ProducedSteelCoilQuantity {
            get {
                return ResourceManager.GetString("ProducedSteelCoilQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Producción.
        /// </summary>
        public static string Production {
            get {
                return ResourceManager.GetString("Production", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prod.
        /// </summary>
        public static string ProductionAbbr {
            get {
                return ResourceManager.GetString("ProductionAbbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cantidad Producida.
        /// </summary>
        public static string ProductionQuantity {
            get {
                return ResourceManager.GetString("ProductionQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C. Prod..
        /// </summary>
        public static string ProductionQuantityAbbr {
            get {
                return ResourceManager.GetString("ProductionQuantityAbbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Producción Servicios.
        /// </summary>
        public static string ProductionServices {
            get {
                return ResourceManager.GetString("ProductionServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Puerta.
        /// </summary>
        public static string Puerta {
            get {
                return ResourceManager.GetString("Puerta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Puerta.
        /// </summary>
        public static string Puerta1 {
            get {
                return ResourceManager.GetString("Puerta1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cantidad.
        /// </summary>
        public static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rectangular.
        /// </summary>
        public static string Rectangular {
            get {
                return ResourceManager.GetString("Rectangular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rectangular.
        /// </summary>
        public static string Rectangular1 {
            get {
                return ResourceManager.GetString("Rectangular1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reproceso.
        /// </summary>
        public static string Reprocessing {
            get {
                return ResourceManager.GetString("Reprocessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rep..
        /// </summary>
        public static string ReprocessingAbbr {
            get {
                return ResourceManager.GetString("ReprocessingAbbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reproceso de bobinas genuinas.
        /// </summary>
        public static string ReprocessingOfGenuineSteelCoils {
            get {
                return ResourceManager.GetString("ReprocessingOfGenuineSteelCoils", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reproceso de bobinas servicio.
        /// </summary>
        public static string ReprocessingOfServiceSteelCoils {
            get {
                return ResourceManager.GetString("ReprocessingOfServiceSteelCoils", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resultados.
        /// </summary>
        public static string Results {
            get {
                return ResourceManager.GetString("Results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resumen.
        /// </summary>
        public static string Resumen {
            get {
                return ResourceManager.GetString("Resumen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resumen.
        /// </summary>
        public static string Resumen1 {
            get {
                return ResourceManager.GetString("Resumen1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retenido.
        /// </summary>
        public static string Retained {
            get {
                return ResourceManager.GetString("Retained", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ret..
        /// </summary>
        public static string RetainedAbbr {
            get {
                return ResourceManager.GetString("RetainedAbbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cantidad Retenida.
        /// </summary>
        public static string RetainedQuantity {
            get {
                return ResourceManager.GetString("RetainedQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C. Ret..
        /// </summary>
        public static string RetainedQuantityAbbr {
            get {
                return ResourceManager.GetString("RetainedQuantityAbbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Muestreado.
        /// </summary>
        public static string Sampled {
            get {
                return ResourceManager.GetString("Sampled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Programa.
        /// </summary>
        public static string Schedule {
            get {
                return ResourceManager.GetString("Schedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Materiales Programados.
        /// </summary>
        public static string ScheduledMaterials {
            get {
                return ResourceManager.GetString("ScheduledMaterials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número de Programa.
        /// </summary>
        public static string ScheduleNumber {
            get {
                return ResourceManager.GetString("ScheduleNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buscar.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtros de Búsqueda.
        /// </summary>
        public static string SearchFilters {
            get {
                return ResourceManager.GetString("SearchFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seguridad.
        /// </summary>
        public static string Seguridad {
            get {
                return ResourceManager.GetString("Seguridad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seguridad.
        /// </summary>
        public static string Seguridad1 {
            get {
                return ResourceManager.GetString("Seguridad1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datos Turno Seleccionado.
        /// </summary>
        public static string SelectedShiftData {
            get {
                return ResourceManager.GetString("SelectedShiftData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secuencia.
        /// </summary>
        public static string Sequence {
            get {
                return ResourceManager.GetString("Sequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serie.
        /// </summary>
        public static string Serie {
            get {
                return ResourceManager.GetString("Serie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Materiales Serie.
        /// </summary>
        public static string SerieMaterials {
            get {
                return ResourceManager.GetString("SerieMaterials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Servicios.
        /// </summary>
        public static string Services {
            get {
                return ResourceManager.GetString("Services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turno.
        /// </summary>
        public static string Shift {
            get {
                return ResourceManager.GetString("Shift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiempo disponible del turno.
        /// </summary>
        public static string ShiftAvailableTime {
            get {
                return ResourceManager.GetString("ShiftAvailableTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Producción Total del Turno.
        /// </summary>
        public static string ShiftTotalProduction {
            get {
                return ResourceManager.GetString("ShiftTotalProduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Velocidad.
        /// </summary>
        public static string Speed {
            get {
                return ResourceManager.GetString("Speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inicio.
        /// </summary>
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bobina.
        /// </summary>
        public static string SteelCoil {
            get {
                return ResourceManager.GetString("SteelCoil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subconcepto.
        /// </summary>
        public static string Subconcept {
            get {
                return ResourceManager.GetString("Subconcept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supervisor.
        /// </summary>
        public static string Supervisor {
            get {
                return ResourceManager.GetString("Supervisor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tablero.
        /// </summary>
        public static string Tablero {
            get {
                return ResourceManager.GetString("Tablero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tablero.
        /// </summary>
        public static string Tablero1 {
            get {
                return ResourceManager.GetString("Tablero1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Espesor.
        /// </summary>
        public static string Thickness {
            get {
                return ResourceManager.GetString("Thickness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiempo de demoras justificadas.
        /// </summary>
        public static string TimeOfJustifiedDelays {
            get {
                return ResourceManager.GetString("TimeOfJustifiedDelays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiempo de bajo ritmo operativo (duración mayor a dos minutos).
        /// </summary>
        public static string TimeOfLowOperativeRythm {
            get {
                return ResourceManager.GetString("TimeOfLowOperativeRythm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiempo de ritmo operativo por hora.
        /// </summary>
        public static string TimeOfOperativeRythmPerHour {
            get {
                return ResourceManager.GetString("TimeOfOperativeRythmPerHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiempo de demoras no justificadas o inexistentes.
        /// </summary>
        public static string TimeOfUnjustifiedDelays {
            get {
                return ResourceManager.GetString("TimeOfUnjustifiedDelays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ton.
        /// </summary>
        public static string TonAbbr {
            get {
                return ResourceManager.GetString("TonAbbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toneladas.
        /// </summary>
        public static string Tons {
            get {
                return ResourceManager.GetString("Tons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiempo No Disponible.
        /// </summary>
        public static string UnavailableTime {
            get {
                return ResourceManager.GetString("UnavailableTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T. No. Disp..
        /// </summary>
        public static string UnavailableTimeAbbr {
            get {
                return ResourceManager.GetString("UnavailableTimeAbbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unidades.
        /// </summary>
        public static string Units {
            get {
                return ResourceManager.GetString("Units", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiempo desprogramado.
        /// </summary>
        public static string UnprogrammedTime {
            get {
                return ResourceManager.GetString("UnprogrammedTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Varilla.
        /// </summary>
        public static string Varilla {
            get {
                return ResourceManager.GetString("Varilla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Varilla.
        /// </summary>
        public static string Varilla1 {
            get {
                return ResourceManager.GetString("Varilla1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ventana.
        /// </summary>
        public static string Ventana {
            get {
                return ResourceManager.GetString("Ventana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ventana.
        /// </summary>
        public static string Ventana1 {
            get {
                return ResourceManager.GetString("Ventana1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peso.
        /// </summary>
        public static string Weight {
            get {
                return ResourceManager.GetString("Weight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ancho.
        /// </summary>
        public static string Width {
            get {
                return ResourceManager.GetString("Width", resourceCulture);
            }
        }
    }
}
