//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Leyendas {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Leyendas.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alambrón.
        /// </summary>
        public static string Alambrón {
            get {
                return ResourceManager.GetString("Alambrón", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bienvenidos.
        /// </summary>
        public static string Bienvenidos {
            get {
                return ResourceManager.GetString("Bienvenidos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gráfico por Colada .
        /// </summary>
        public static string chart_Coladas_Subtitulo {
            get {
                return ResourceManager.GetString("chart_Coladas_Subtitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grafico Rollo a Rollo.
        /// </summary>
        public static string chart_RolloRollo_Subtitulo {
            get {
                return ResourceManager.GetString("chart_RolloRollo_Subtitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sin información para mostrar..
        /// </summary>
        public static string chart_SinInformacion {
            get {
                return ResourceManager.GetString("chart_SinInformacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sin información para mostrar..
        /// </summary>
        public static string chartEmpty_Msg {
            get {
                return ResourceManager.GetString("chartEmpty_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe seleccionar al menos un indicador para graficar..
        /// </summary>
        public static string chartEmpty_Multi_Subtitulo {
            get {
                return ResourceManager.GetString("chartEmpty_Multi_Subtitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe seleccionar al menos una opción para graficar..
        /// </summary>
        public static string chartEmpty_Subtitulo {
            get {
                return ResourceManager.GetString("chartEmpty_Subtitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sin información para mostrar..
        /// </summary>
        public static string chartEmpty_Titulo {
            get {
                return ResourceManager.GetString("chartEmpty_Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cortina.
        /// </summary>
        public static string Cortina {
            get {
                return ResourceManager.GetString("Cortina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cuadrado.
        /// </summary>
        public static string Cuadrado {
            get {
                return ResourceManager.GetString("Cuadrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duela.
        /// </summary>
        public static string Duela {
            get {
                return ResourceManager.GetString("Duela", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acero laminado en caliente.
        /// </summary>
        public static string Ejem_Prod1 {
            get {
                return ResourceManager.GetString("Ejem_Prod1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variedad de diámetros.
        /// </summary>
        public static string Ejem_Prod2 {
            get {
                return ResourceManager.GetString("Ejem_Prod2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resistente.
        /// </summary>
        public static string Ejem_Prod3 {
            get {
                return ResourceManager.GetString("Ejem_Prod3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corrugado especial.
        /// </summary>
        public static string Ejem_Prod4 {
            get {
                return ResourceManager.GetString("Ejem_Prod4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resistencia estructural.
        /// </summary>
        public static string Ejem_Prod5 {
            get {
                return ResourceManager.GetString("Ejem_Prod5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variedad de Calibres.
        /// </summary>
        public static string Ejem_Prod6 {
            get {
                return ResourceManager.GetString("Ejem_Prod6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Durabilidad y resistencia estructural.
        /// </summary>
        public static string Ejem_Text1 {
            get {
                return ResourceManager.GetString("Ejem_Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Productos derivados de laminación en caliente de palanquillas. Su sección es circular y la superficie lisa o corrugada..
        /// </summary>
        public static string Ejem_Text2 {
            get {
                return ResourceManager.GetString("Ejem_Text2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Productos y Servicios.
        /// </summary>
        public static string Ejem_Tit1 {
            get {
                return ResourceManager.GetString("Ejem_Tit1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aceros Largos.
        /// </summary>
        public static string Ejem_Tit2 {
            get {
                return ResourceManager.GetString("Ejem_Tit2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resistencia y variedad de formas.
        /// </summary>
        public static string Ejem2_Text1 {
            get {
                return ResourceManager.GetString("Ejem2_Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Los perfiles Ternium son fabricados con acero procesado en roladoras y molinos, con acabado negro, galvanizado y pintado. Disponibles en una amplia variedad de diseños para usos específicos, que van desde la periferia para ventanas, marcos y puertas, hasta polines y perfiles estructurales..
        /// </summary>
        public static string Ejem2_Text2 {
            get {
                return ResourceManager.GetString("Ejem2_Text2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Productos.
        /// </summary>
        public static string Ejem2_Tit1 {
            get {
                return ResourceManager.GetString("Ejem2_Tit1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perfiles.
        /// </summary>
        public static string Ejem2_Tit2 {
            get {
                return ResourceManager.GetString("Ejem2_Tit2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Español.
        /// </summary>
        public static string Español {
            get {
                return ResourceManager.GetString("Español", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingles.
        /// </summary>
        public static string Ingles {
            get {
                return ResourceManager.GetString("Ingles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inicio.
        /// </summary>
        public static string Inicio {
            get {
                return ResourceManager.GetString("Inicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inicio.
        /// </summary>
        public static string Inicio1 {
            get {
                return ResourceManager.GetString("Inicio1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Japones.
        /// </summary>
        public static string Japones {
            get {
                return ResourceManager.GetString("Japones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Español.
        /// </summary>
        public static string L_Español {
            get {
                return ResourceManager.GetString("L_Español", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingles.
        /// </summary>
        public static string L_Ingles {
            get {
                return ResourceManager.GetString("L_Ingles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Japones.
        /// </summary>
        public static string L_Japones {
            get {
                return ResourceManager.GetString("L_Japones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lineas.
        /// </summary>
        public static string L_LineasTooltip {
            get {
                return ResourceManager.GetString("L_LineasTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&lt;br/&gt;I&lt;br/&gt;N&lt;br/&gt;E&lt;br/&gt;A&lt;br/&gt;S.
        /// </summary>
        public static string L_LineasVertical {
            get {
                return ResourceManager.GetString("L_LineasVertical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logo Casa.
        /// </summary>
        public static string L_LogoCasa {
            get {
                return ResourceManager.GetString("L_LogoCasa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disculpe las molestias, esta pagina esta en construcción..
        /// </summary>
        public static string L_MsgEnConstruccion {
            get {
                return ResourceManager.GetString("L_MsgEnConstruccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es posible que haya ocurrido un error inesperado..
        /// </summary>
        public static string L_MsgErrorApp1 {
            get {
                return ResourceManager.GetString("L_MsgErrorApp1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Los administradores del sistema han sido notificados de este evento..
        /// </summary>
        public static string L_MsgErrorApp2 {
            get {
                return ResourceManager.GetString("L_MsgErrorApp2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lamentamos los inconvenientes ocasionados..
        /// </summary>
        public static string L_MsgErrorApp3 {
            get {
                return ResourceManager.GetString("L_MsgErrorApp3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disculpa, ocurrió un error al procesar su solicitud..
        /// </summary>
        public static string L_MsgErrorGral {
            get {
                return ResourceManager.GetString("L_MsgErrorGral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lo sentimos, usted no tiene accesso a esta caracteristica del sistema o no ingresó su usuario/clave..
        /// </summary>
        public static string L_MsgSinAcceso {
            get {
                return ResourceManager.GetString("L_MsgSinAcceso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Piso de Planta.
        /// </summary>
        public static string L_PisodePlanta {
            get {
                return ResourceManager.GetString("L_PisodePlanta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portugues.
        /// </summary>
        public static string L_Portugues {
            get {
                return ResourceManager.GetString("L_Portugues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abrir.
        /// </summary>
        public static string L_SliderAbrir {
            get {
                return ResourceManager.GetString("L_SliderAbrir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cerrar.
        /// </summary>
        public static string L_SliderCerrar {
            get {
                return ResourceManager.GetString("L_SliderCerrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A&lt;br/&gt;C&lt;br/&gt;T&lt;br/&gt;U&lt;br/&gt;A&lt;br/&gt;L.
        /// </summary>
        public static string lblActual {
            get {
                return ResourceManager.GetString("lblActual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actualizar.
        /// </summary>
        public static string lblActualizar {
            get {
                return ResourceManager.GetString("lblActualizar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A&lt;br/&gt;C&lt;br/&gt;U&lt;br/&gt;M&lt;br/&gt;U&lt;br/&gt;L&lt;br/&gt;A&lt;br/&gt;D&lt;br/&gt;O.
        /// </summary>
        public static string lblAcum {
            get {
                return ResourceManager.GetString("lblAcum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agosto.
        /// </summary>
        public static string lblAgust {
            get {
                return ResourceManager.GetString("lblAgust", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string lblAll {
            get {
                return ResourceManager.GetString("lblAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analizador.
        /// </summary>
        public static string lblAnalizadorTitulo {
            get {
                return ResourceManager.GetString("lblAnalizadorTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A&lt;br /&gt;P&lt;br /&gt;E&lt;br /&gt;R&lt;br /&gt;T&lt;br /&gt;U&lt;br /&gt;R&lt;br /&gt;A.
        /// </summary>
        public static string lblApertura {
            get {
                return ResourceManager.GetString("lblApertura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abr.
        /// </summary>
        public static string lblApr {
            get {
                return ResourceManager.GetString("lblApr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abril.
        /// </summary>
        public static string lblApril {
            get {
                return ResourceManager.GetString("lblApril", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ago.
        /// </summary>
        public static string lblAug {
            get {
                return ResourceManager.GetString("lblAug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bajo Ritmo.
        /// </summary>
        public static string lblBajoRitmo {
            get {
                return ResourceManager.GetString("lblBajoRitmo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ciclo.
        /// </summary>
        public static string lblCiclo {
            get {
                return ResourceManager.GetString("lblCiclo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jul.
        /// </summary>
        public static string lblcJuly {
            get {
                return ResourceManager.GetString("lblcJuly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jun.
        /// </summary>
        public static string lblcJune {
            get {
                return ResourceManager.GetString("lblcJune", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to May.
        /// </summary>
        public static string lblcMay {
            get {
                return ResourceManager.GetString("lblcMay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Columnas.
        /// </summary>
        public static string lblCmbCols {
            get {
                return ResourceManager.GetString("lblCmbCols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicadores.
        /// </summary>
        public static string lblCmbIndicators {
            get {
                return ResourceManager.GetString("lblCmbIndicators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filas.
        /// </summary>
        public static string lblCmbRows {
            get {
                return ResourceManager.GetString("lblCmbRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unidades.
        /// </summary>
        public static string lblCmbUnits {
            get {
                return ResourceManager.GetString("lblCmbUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C&lt;br/&gt;O&lt;br/&gt;L&lt;br/&gt;A&lt;br/&gt;D&lt;br/&gt;A.
        /// </summary>
        public static string lblColada {
            get {
                return ResourceManager.GetString("lblColada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dic.
        /// </summary>
        public static string lblDec {
            get {
                return ResourceManager.GetString("lblDec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diciembre.
        /// </summary>
        public static string lblDecember {
            get {
                return ResourceManager.GetString("lblDecember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminar todos los Filtros.
        /// </summary>
        public static string lblDeleteAllFilters {
            get {
                return ResourceManager.GetString("lblDeleteAllFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demoras.
        /// </summary>
        public static string lblDemoras {
            get {
                return ResourceManager.GetString("lblDemoras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desvíos.
        /// </summary>
        public static string lblDesviosTitle {
            get {
                return ResourceManager.GetString("lblDesviosTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe Seleccionar diferentes dimensiones..
        /// </summary>
        public static string lblDiferentDimensions {
            get {
                return ResourceManager.GetString("lblDiferentDimensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dimensiones.
        /// </summary>
        public static string lblDimensionesAnalyzer {
            get {
                return ResourceManager.GetString("lblDimensionesAnalyzer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mantenimiento.
        /// </summary>
        public static string lblEquiposMtto {
            get {
                return ResourceManager.GetString("lblEquiposMtto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipos.
        /// </summary>
        public static string lblEquiposUT {
            get {
                return ResourceManager.GetString("lblEquiposUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E&lt;br/&gt;V&lt;br/&gt;O&lt;br/&gt;L&lt;br/&gt;U&lt;br/&gt;C&lt;br/&gt;I&lt;br/&gt;O&lt;br/&gt;N.
        /// </summary>
        public static string lblEvolucion {
            get {
                return ResourceManager.GetString("lblEvolucion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feb.
        /// </summary>
        public static string lblFeb {
            get {
                return ResourceManager.GetString("lblFeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Febrero.
        /// </summary>
        public static string lblFebruary {
            get {
                return ResourceManager.GetString("lblFebruary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtros.
        /// </summary>
        public static string lblFiltros {
            get {
                return ResourceManager.GetString("lblFiltros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Viernes.
        /// </summary>
        public static string lblFriday {
            get {
                return ResourceManager.GetString("lblFriday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desde.
        /// </summary>
        public static string lblFrom {
            get {
                return ResourceManager.GetString("lblFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Herramientas.
        /// </summary>
        public static string lblHerramientas {
            get {
                return ResourceManager.GetString("lblHerramientas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H&lt;br/&gt;I&lt;br/&gt;S&lt;br/&gt;T&lt;br/&gt;O&lt;br/&gt;G&lt;br/&gt;R&lt;br/&gt;A&lt;br/&gt;M&lt;br/&gt;A.
        /// </summary>
        public static string lblHistograma {
            get {
                return ResourceManager.GetString("lblHistograma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H&lt;br/&gt;I&lt;br/&gt;S&lt;br/&gt;T&lt;br/&gt;O&lt;br/&gt;R&lt;br/&gt;I&lt;br/&gt;C&lt;br/&gt;O.
        /// </summary>
        public static string lblHistorico {
            get {
                return ResourceManager.GetString("lblHistorico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicadores.
        /// </summary>
        public static string lblIndicadores {
            get {
                return ResourceManager.GetString("lblIndicadores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interrupciones.
        /// </summary>
        public static string lblInterruptions {
            get {
                return ResourceManager.GetString("lblInterruptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ene.
        /// </summary>
        public static string lblJan {
            get {
                return ResourceManager.GetString("lblJan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enero.
        /// </summary>
        public static string lblJanuary {
            get {
                return ResourceManager.GetString("lblJanuary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Julio.
        /// </summary>
        public static string lblJuly {
            get {
                return ResourceManager.GetString("lblJuly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Junio.
        /// </summary>
        public static string lblJune {
            get {
                return ResourceManager.GetString("lblJune", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linea:.
        /// </summary>
        public static string lblLine {
            get {
                return ResourceManager.GetString("lblLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mar.
        /// </summary>
        public static string lblMar {
            get {
                return ResourceManager.GetString("lblMar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marzo.
        /// </summary>
        public static string lblMarch {
            get {
                return ResourceManager.GetString("lblMarch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mayo.
        /// </summary>
        public static string lblMay {
            get {
                return ResourceManager.GetString("lblMay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menú.
        /// </summary>
        public static string lblMenu {
            get {
                return ResourceManager.GetString("lblMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lunes.
        /// </summary>
        public static string lblMonday {
            get {
                return ResourceManager.GetString("lblMonday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encontró información..
        /// </summary>
        public static string lblNotInfo {
            get {
                return ResourceManager.GetString("lblNotInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encontró información para la fecha seleccionada..
        /// </summary>
        public static string lblNotInterruptions {
            get {
                return ResourceManager.GetString("lblNotInterruptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nov.
        /// </summary>
        public static string lblNov {
            get {
                return ResourceManager.GetString("lblNov", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Noviembre.
        /// </summary>
        public static string lblNovember {
            get {
                return ResourceManager.GetString("lblNovember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oct.
        /// </summary>
        public static string lblOct {
            get {
                return ResourceManager.GetString("lblOct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Octubre.
        /// </summary>
        public static string lblOctuber {
            get {
                return ResourceManager.GetString("lblOctuber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P&lt;br/&gt;A&lt;br/&gt;R&lt;br/&gt;E&lt;br/&gt;T&lt;br/&gt;O.
        /// </summary>
        public static string lblPareto {
            get {
                return ResourceManager.GetString("lblPareto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planta:.
        /// </summary>
        public static string lblPlant {
            get {
                return ResourceManager.GetString("lblPlant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R&lt;br/&gt;A&lt;br/&gt;N&lt;br/&gt;G&lt;br/&gt;O.
        /// </summary>
        public static string lblRango {
            get {
                return ResourceManager.GetString("lblRango", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resumen de indicadores.
        /// </summary>
        public static string lblResumenInd {
            get {
                return ResourceManager.GetString("lblResumenInd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R&lt;br/&gt;O&lt;br/&gt;L&lt;br/&gt;L&lt;br/&gt;O.
        /// </summary>
        public static string lblRollo {
            get {
                return ResourceManager.GetString("lblRollo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sabado.
        /// </summary>
        public static string lblSaturday {
            get {
                return ResourceManager.GetString("lblSaturday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reporte Resumen Semaforos.
        /// </summary>
        public static string lblSemaphoreTitle {
            get {
                return ResourceManager.GetString("lblSemaphoreTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sep.
        /// </summary>
        public static string lblSep {
            get {
                return ResourceManager.GetString("lblSep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Septiembre.
        /// </summary>
        public static string lblSeptember {
            get {
                return ResourceManager.GetString("lblSeptember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sesion.
        /// </summary>
        public static string lblSession {
            get {
                return ResourceManager.GetString("lblSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mostrar / Oculta Filtros.
        /// </summary>
        public static string lblShowHideFilters {
            get {
                return ResourceManager.GetString("lblShowHideFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paradas.
        /// </summary>
        public static string lblStops {
            get {
                return ResourceManager.GetString("lblStops", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domingo.
        /// </summary>
        public static string lblSunday {
            get {
                return ResourceManager.GetString("lblSunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jueves.
        /// </summary>
        public static string lblThursday {
            get {
                return ResourceManager.GetString("lblThursday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiempos.
        /// </summary>
        public static string lblTimepos {
            get {
                return ResourceManager.GetString("lblTimepos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hasta.
        /// </summary>
        public static string lblTo {
            get {
                return ResourceManager.GetString("lblTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Martes.
        /// </summary>
        public static string lblTuesday {
            get {
                return ResourceManager.GetString("lblTuesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miercoles.
        /// </summary>
        public static string lblWednesday {
            get {
                return ResourceManager.GetString("lblWednesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lineas.
        /// </summary>
        public static string LineasTooltip {
            get {
                return ResourceManager.GetString("LineasTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&lt;br/&gt;I&lt;br/&gt;N&lt;br/&gt;E&lt;br/&gt;A&lt;br/&gt;S.
        /// </summary>
        public static string LineasVertical {
            get {
                return ResourceManager.GetString("LineasVertical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logo Casa.
        /// </summary>
        public static string LogoCasa {
            get {
                return ResourceManager.GetString("LogoCasa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marco.
        /// </summary>
        public static string Marco {
            get {
                return ResourceManager.GetString("Marco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al obtener la estructura JSON del calendario.
        /// </summary>
        public static string msg_error_getcalendar {
            get {
                return ResourceManager.GetString("msg_error_getcalendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al obtener las dimensiones.
        /// </summary>
        public static string msg_error_getdimensions {
            get {
                return ResourceManager.GetString("msg_error_getdimensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al obtener los Filtros.
        /// </summary>
        public static string msg_error_getFilters {
            get {
                return ResourceManager.GetString("msg_error_getFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al obtener los eventos del Gantt.
        /// </summary>
        public static string msg_error_getGanttEvents {
            get {
                return ResourceManager.GetString("msg_error_getGanttEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al obtener la Estructura de la Grid..
        /// </summary>
        public static string msg_error_getgridstruct {
            get {
                return ResourceManager.GetString("msg_error_getgridstruct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al obtener la estructura JSON de los indicadores.
        /// </summary>
        public static string msg_error_getidnicators {
            get {
                return ResourceManager.GetString("msg_error_getidnicators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al obtener los indicadores para los SubFiltros del Chart.
        /// </summary>
        public static string msg_error_getindicatorsChart {
            get {
                return ResourceManager.GetString("msg_error_getindicatorsChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al obtener el JSON del flexigrid en la pestaña de Datos..
        /// </summary>
        public static string msg_error_getJsonFlxData {
            get {
                return ResourceManager.GetString("msg_error_getJsonFlxData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al obtener la estructura JSON para el Arbol.
        /// </summary>
        public static string msg_error_getTreeKeys {
            get {
                return ResourceManager.GetString("msg_error_getTreeKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al obtener las unidades para los subfiltros del Chart.
        /// </summary>
        public static string msg_error_getunitsChart {
            get {
                return ResourceManager.GetString("msg_error_getunitsChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al obtener las variaciones para los Subfiltros del Chart.
        /// </summary>
        public static string msg_error_getvariationsChart {
            get {
                return ResourceManager.GetString("msg_error_getvariationsChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Opening Data Base..
        /// </summary>
        public static string msg_error_open_db {
            get {
                return ResourceManager.GetString("msg_error_open_db", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se ha configurado ningún template con los parametros IdLine: {0}, IdTbl: {1}, IdPeriod: {2}, IdTypeTemplate: {3}.
        /// </summary>
        public static string msg_NoTemplateConfigurated {
            get {
                return ResourceManager.GetString("msg_NoTemplateConfigurated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agregar.
        /// </summary>
        public static string msg_tooltip_add {
            get {
                return ResourceManager.GetString("msg_tooltip_add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disculpa, ocurrió un error al procesar su solicitud..
        /// </summary>
        public static string MsgErrorGral {
            get {
                return ResourceManager.GetString("MsgErrorGral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pasamanos.
        /// </summary>
        public static string Pasamanos {
            get {
                return ResourceManager.GetString("Pasamanos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Piso de Planta.
        /// </summary>
        public static string PisodePlanta {
            get {
                return ResourceManager.GetString("PisodePlanta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portugues.
        /// </summary>
        public static string Portugues {
            get {
                return ResourceManager.GetString("Portugues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Producción.
        /// </summary>
        public static string Produccion {
            get {
                return ResourceManager.GetString("Produccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Producción.
        /// </summary>
        public static string Producción {
            get {
                return ResourceManager.GetString("Producción", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Puerta.
        /// </summary>
        public static string Puerta {
            get {
                return ResourceManager.GetString("Puerta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rectangular.
        /// </summary>
        public static string Rectangular {
            get {
                return ResourceManager.GetString("Rectangular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resumen.
        /// </summary>
        public static string Resumen {
            get {
                return ResourceManager.GetString("Resumen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resumen.
        /// </summary>
        public static string Resumen1 {
            get {
                return ResourceManager.GetString("Resumen1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seguridad.
        /// </summary>
        public static string Seguridad {
            get {
                return ResourceManager.GetString("Seguridad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seguridad.
        /// </summary>
        public static string Seguridad1 {
            get {
                return ResourceManager.GetString("Seguridad1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abrir.
        /// </summary>
        public static string SliderAbrir {
            get {
                return ResourceManager.GetString("SliderAbrir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cerrar.
        /// </summary>
        public static string SliderCerrar {
            get {
                return ResourceManager.GetString("SliderCerrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tablero.
        /// </summary>
        public static string Tablero {
            get {
                return ResourceManager.GetString("Tablero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No su pudo agregar la linea a la vista. Intente mas tarde..
        /// </summary>
        public static string taco_msg_error_addLineToView {
            get {
                return ResourceManager.GetString("taco_msg_error_addLineToView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No su pudo crear la nueva vista. Intente mas tarde..
        /// </summary>
        public static string taco_msg_error_addView {
            get {
                return ResourceManager.GetString("taco_msg_error_addView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se pudo cambiar el orden a la linea. Intente mas tarde..
        /// </summary>
        public static string taco_msg_error_changeOrderLineToView {
            get {
                return ResourceManager.GetString("taco_msg_error_changeOrderLineToView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se pudo desasignar la linea de la vista. Intente mas tarde..
        /// </summary>
        public static string taco_msg_error_deleteLineToView {
            get {
                return ResourceManager.GetString("taco_msg_error_deleteLineToView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se pudo eliminar la vista. Intente mas tarde..
        /// </summary>
        public static string taco_msg_error_deleteView {
            get {
                return ResourceManager.GetString("taco_msg_error_deleteView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se pudo obtener si el gantt esta habilitado para una linea..
        /// </summary>
        public static string taco_msg_error_enableGantt {
            get {
                return ResourceManager.GetString("taco_msg_error_enableGantt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se pudieron obtener las lineas. Intente mas tarde..
        /// </summary>
        public static string taco_msg_error_getAllLines {
            get {
                return ResourceManager.GetString("taco_msg_error_getAllLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se pudo obtener los criterios para la configuración..
        /// </summary>
        public static string taco_msg_error_getCriterias {
            get {
                return ResourceManager.GetString("taco_msg_error_getCriterias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se pudo obtener el reporte, debido a la conexión hacia alguna linea. Intente mas tarde..
        /// </summary>
        public static string taco_msg_error_getGrid {
            get {
                return ResourceManager.GetString("taco_msg_error_getGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encontró la linea. Intente mas tarde..
        /// </summary>
        public static string taco_msg_error_getLineByDescription {
            get {
                return ResourceManager.GetString("taco_msg_error_getLineByDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se pudieron obtener las lineas del reporte. Intente mas tarde..
        /// </summary>
        public static string taco_msg_error_getLinesByTemplate {
            get {
                return ResourceManager.GetString("taco_msg_error_getLinesByTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se pudieron obtener las lineas. Intente mas tarde..
        /// </summary>
        public static string taco_msg_error_getLinesByViewCustom {
            get {
                return ResourceManager.GetString("taco_msg_error_getLinesByViewCustom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se pudo obtener el arbol de lineas. Intente mas tarde..
        /// </summary>
        public static string taco_msg_error_getTreeAreaLines {
            get {
                return ResourceManager.GetString("taco_msg_error_getTreeAreaLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se pudo obtener la url de la linea..
        /// </summary>
        public static string taco_msg_error_getUrlSGLByRow {
            get {
                return ResourceManager.GetString("taco_msg_error_getUrlSGLByRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocurrio un erro al realizar una consulta. Intente mas tarde..
        /// </summary>
        public static string taco_msg_error_getViewCustom {
            get {
                return ResourceManager.GetString("taco_msg_error_getViewCustom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se pudieron obtener las vistas. Intente mas tarde..
        /// </summary>
        public static string taco_msg_error_getViews {
            get {
                return ResourceManager.GetString("taco_msg_error_getViews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se pudo establecer la vista como predeterminada. Intente mas tarde..
        /// </summary>
        public static string taco_msg_error_setView {
            get {
                return ResourceManager.GetString("taco_msg_error_setView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Varilla.
        /// </summary>
        public static string Varilla {
            get {
                return ResourceManager.GetString("Varilla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ventana.
        /// </summary>
        public static string Ventana {
            get {
                return ResourceManager.GetString("Ventana", resourceCulture);
            }
        }
    }
}
